[tools]
fzf = "latest"
gcloud = "latest"
glab = "latest"
glow = "latest"
helm = "latest"
jq = "latest"
jsonnet = "latest"
k9s = "latest"
kubectl = "latest"
opentofu = "1.8.0"
python = "latest"
pipenv = "latest"
pipx = "latest"
semtag = "latest"
semver = "latest"
shellcheck = "latest"
shellspec = "latest"
shfmt = "latest"
starship = "latest"
steampipe = "latest"
terraform-docs = "latest"
yamlfmt = "latest"
yamllint = "latest"
yamlscript = "latest"
yq = "latest"
zoxide = "latest"
node = "latest"
